### ISSUE TITLE
Accuracy issues

### ISSUE THREAD

**Issue by schombert** [OpenVicProject/OpenVic-Simulation#213]
I see things in your fixed point implementation such as
```
static constexpr fixed_point_t _0_05() {
	return _0_01() * 5;
}
```
The issue with this is that your fixed point representation does not represent 0.01 exactly: you store 0.01 + e for some small e error value. Thus returning `_0_01() * 5` is returning (0.01 + e)*5 = 0.05 + 5*e. However, the magnitude of the error required is roughly the same for both values, so this value has an error that is around 4*e larger than it has to be.

**Comment by schombert** [comment]
Here is another example where the same issue might give you problems. You represent 0.1 internally as the value 6,553 and 0.5 as 32,768. So, if someone wrote a scripted effect that added 0.1 five times to an internal variable, they would end up with 32,765 inside the fixed point value storing their variable in game. If they then compared that variable to 0.5 in another script function, the result would be false, because 32,765 is less than 32,768. (0.1 + 0.1 + 0.1 + 0.1 + 0.1 < 0.5). The result comes out as expected in Victoria 2 because it stores values with decimal precision. If you want to copy the behavior of V2 exactly, you may want to use decimal precision. If you only care about getting things approximately right, you could add an epsilon factor to your comparisons that is greater than the error you expect to see in practice.

**Comment by schombert** [comment]
@wvpm

**Comment by wvpm** [comment]
Correct. This is something we discussed earlier internally. There were some arguments for and against using a decimal representation to solve such inaccuracies. As for _0_05 and such cases specifically, we could improve the accuracy yeah.

@Spartan322 what are your thoughts?

**Comment by Spartan322** [comment]
We don't expect fixed points to be accurate like that, they're not supposed to be, you're not supposed to compare them using direct equality anyway, whether floating point or fixed point, you always use an epsilon, the only difference with fixed point vs. floating point is that you can have a compile time epsilon where as with floating point it depends on how many digits the floating point has.

**Comment by schombert** [comment]
While I am here, your `floor()` function is incorrect for negative values, as are any functions defined in terms of it

**Comment by schombert** [comment]
Sorry, miswrote a comment. I believe that your `get_frac()` is incorrect for negative values. A small negative fraction will yield a large positive fraction.

**Comment by schombert** [comment]
Yes, yes, I should read the comments. I got lost thinking about rounding and what static_cast<float>(NumberUtils::round_to_int64((value / static_cast<float>(ONE)) * 100000.0f)) / 100000.0f was accomplishing
