### ISSUE TITLE
Store tax rate

### ISSUE THREAD

**Issue by wvpm** [OpenVicProject/OpenVic-Simulation#226]
### Simulation
Each country can determine its own tax rates for each strata (poor, middle and rich). The value ranges from 0% to 100% of the pop income. Tax rate is restricted by the modifiers `min_tax` and `max_tax`.

When starting a new game, tax rate is initialised at 50%. If `min_tax` or `max_tax` don't allow that, it is set to as close as possible to 50%. 

Tasks:
- [x] Create tax rates per strata properties for CountryInstance.
- [ ] Create a method to update the tax rate per strata. This method ensures the tax rate is between `min_tax` and `max_tax`.
- [x] Handle edge cases where `min_tax` > `max_tax` (test how Victoria 2 handles it).
- [x] Initialise the tax rates to 50% using the created method.

### UI
The UI part could be split off as a separate issue if desired.

The tax rate can be adjusted using the sliders in the budget menu. The sliders are bound to the tax rate. This binding goes both ways. If the slider changes, the tax rate changes. If the tax rate changes, the slider changes. Only the player country has this binding.

- [x] Create slider per strata
- [ ] Set the sliders to the tax rates of the player country
- [ ] Set the tax rate to the slider value when sliding.

**Comment by Juliusfrank11** [comment]
WIP pr: https://github.com/OpenVicProject/OpenVic-Simulation/pull/231
